[tool.uv]
package = false

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vlm-latent-piaa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentations",
    "opencv-python-headless",
    "torch==2.6.0+cu126",
    "transformers",
    "datasets",
    "accelerate",
    "peft",
    "pillow",
    "torchvision",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "triton @ file:/work/gh35/h35008/triton-cu126/python",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126"},
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true


